Repository newrelic/newrelic-node-apollo-server-plugin, pull requests merged in 2020-10, with the labels that each got.

#40 Third party license notices
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: ready for review, risk: none, semver: patch

#41 Capture query in operation segment attributes
  lib/create-plugin.js
  lib/query-utils.js
  tests/unit/query-utils.test.js
  tests/versioned/attributes-tests.js
Labels: ready for review, risk: medium, semver: minor

#48 Add AWS Lambda versioned tests
  .gitignore
  README.md
  THIRD_PARTY_NOTICES.md
  tests/versioned/apollo-server-lambda/apollo-server-lambda-setup.js
  tests/versioned/apollo-server-lambda/attributes-tests.js
  tests/versioned/apollo-server-lambda/errors-tests.js
  tests/versioned/apollo-server-lambda/lambda-test-utils.js
  tests/versioned/apollo-server-lambda/newrelic.js
  tests/versioned/apollo-server-lambda/package.json
  tests/versioned/apollo-server-lambda/segments.test.js
  tests/versioned/apollo-server-lambda/transaction-naming-tests.js
  third_party_manifest.json
Labels: risk: low, semver: patch

#49 Remove template text from readme
  README.md
Labels: ready for review, risk: none, semver: patch

#50 Readme fix
  README.md
Labels: ready for review, risk: none, semver: patch

#51 Update readme with plugin timings recommendations
  README.md
Labels: risk: none, semver: patch

#53 Bumps object-path dev sub-dep to 0.11.5 to clear up audit warnings.
  package-lock.json
Labels: risk: low, semver: patch

#54 Make the repo Community Plus
  .github/workflows/repolinter.yml
  README.md
Labels: ready for review, risk: none, semver: patch

#55 Add release notes for initial release
  NEWS.md
Labels: ready for review, risk: none, semver: minor

#58 Release notes for v0.1.1
  NEWS.md
Labels: risk: low, semver: patch
