Repository newrelic/newrelic-node-apollo-server-plugin, pull requests merged in 2021-07, with the labels that each got.

#97 Consistent trans naming
  lib/create-plugin.js
  tests/versioned/apollo-federation/segments.test.js
  tests/versioned/apollo-federation/transaction-naming.test.js
  tests/versioned/apollo-server-fastify/segments.test.js
  tests/versioned/apollo-server-hapi/segments.test.js
  tests/versioned/apollo-server-koa/segments.test.js
  tests/versioned/apollo-server-lambda/segments.test.js
  tests/versioned/apollo-server-lambda/transaction-naming-tests.js
  tests/versioned/common.js
  tests/versioned/express-segments-default-tests.js
  tests/versioned/express-segments-scalar-tests.js
  tests/versioned/transaction-naming-tests.js
Labels: risk: low, semver: minor

#96 set captureIntrospectionQueries default to be false
  README.md
  lib/create-plugin.js
  tests/integration/config-capture-introspection-queries.test.js
Labels: risk: low, semver: patch

#100 added defensive code around items that lack a name property, also add…
  lib/create-plugin.js
  tests/versioned/apollo-federation/federated-gateway-server-setup.js
  tests/versioned/apollo-federation/transaction-inline-fragments.test.js
Labels: risk: low, semver: patch

#102 Update Readme with Federated Support
  README.md
  tests/versioned/apollo-federation/package.json
  tests/versioned/apollo-server-express/package.json
  tests/versioned/apollo-server-fastify/package.json
  tests/versioned/apollo-server-hapi/package.json
  tests/versioned/apollo-server-koa/package.json
  tests/versioned/apollo-server-lambda/package.json
  tests/versioned/apollo-server/package.json
Labels: risk: low, semver: patch

#104 Move federated support section in readme
  README.md
Labels: risk: none, semver: patch

#107 Release v0.3.0
  NEWS.md
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk: low, semver: minor

#109 Drop node 10 support
  .github/workflows/ci-workflow.yml
  package.json
  tests/versioned/apollo-server-express/package.json
  tests/versioned/apollo-server-fastify/package.json
  tests/versioned/apollo-server-hapi/package.json
  tests/versioned/apollo-server-koa/package.json
  tests/versioned/apollo-server-lambda/package.json
  tests/versioned/apollo-server/package.json
Labels: risk: low, semver: major

#113 Deepest unique naming
  README.md
  docs/metrics.md
  docs/segments-and-spans.md
  docs/transactions.md
  lib/create-plugin.js
  tests/integration/config-capture-scalars.test.js
  tests/integration/metrics.test.js
  tests/versioned/apollo-federation/package.json
  tests/versioned/apollo-federation/segments.test.js
  tests/versioned/apollo-federation/sub-graph-transactions.test.js
  tests/versioned/apollo-federation/transaction-naming.test.js
  tests/versioned/apollo-server-fastify/segments.test.js
  tests/versioned/apollo-server-hapi/segments.test.js
  tests/versioned/apollo-server-koa/segments.test.js
  tests/versioned/apollo-server-lambda/attributes-tests.js
  tests/versioned/apollo-server-lambda/errors-tests.js
  tests/versioned/apollo-server-lambda/segments.test.js
  tests/versioned/apollo-server-lambda/transaction-naming-tests.js
  tests/versioned/attributes-tests.js
  tests/versioned/errors-tests.js
  tests/versioned/express-segments-default-tests.js
  tests/versioned/express-segments-scalar-tests.js
  tests/versioned/transaction-naming-tests.js
Labels: risk: low, semver: major

#112 Ignore health check and service definition queries received from Federated servers
  README.md
  lib/create-plugin.js
  tests/versioned/apollo-federation/federated-gateway-server-setup.js
  tests/versioned/apollo-federation/package.json
  tests/versioned/apollo-federation/service-definition-and-healthcheck-filtering.test.js
  tests/versioned/transaction-naming-tests.js
Labels: risk: low, semver: patch

#114 removed pinning versioned tests to <3.0.0
  tests/versioned/apollo-federation/package.json
  tests/versioned/apollo-server-express/package.json
  tests/versioned/apollo-server-fastify/package.json
  tests/versioned/apollo-server-hapi/package.json
  tests/versioned/apollo-server-koa/package.json
  tests/versioned/apollo-server-lambda/package.json
  tests/versioned/apollo-server/package.json
Labels: risk: low, semver: patch

#121 Release v1.0.0
  NEWS.md
Labels: risk: low, semver: major
